
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

    container_name: php
    network_mode: host
    volumes:
      - ./content:/var/www/html/
      - ./content/uploaded:/var/www/html/uploaded

    command: php -S 0.0.0.0:1234

    tty: true

  db:
    build:
      context: .
      dockerfile: Dockerfile_db
      args:
        UID: 1000

    container_name: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres

    user: "postgres:postgres"

    volumes:
      - ./sql_scripts:/var/lib/postgresql/scripts

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    network_mode: host