
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    network_mode: host
    volumes:
      - ./content:/var/www/html/

    command: php -S 0.0.0.0:1234

    tty: true

  db:
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/postgres

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    network_mode: host

volumes:
  mysql-data: